package app.readribbon.core

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One handiwork per book, sized by the book (build book §2.9).
 * Size is set once from the book's word count when a reading opens, mapped
 * into three drawn sizes rather than a continuous scale — a continuous
 * scale invites comparison; three sizes read as a fact about the book.
 * Decision — the small/medium boundary. The build book's table says small
 * is "under ~5,000 words," but its own example columns contradict that:
 * Philippians (2,219 WEB words), Ruth (2,436) and James (2,249) are listed
 * as medium, while every listed small book is under 650. The examples
 * govern. The boundary sits at 750 — the natural gap in the real
 * distribution (Obadiah 619 → Titus 904) — so that exactly the named
 * books land small. The large boundary (~20,000) agrees with its examples
 * and stands.
 */
@Serializable
enum class FireScale {
    small,      // the single-sitting books — Philemon, Jude, 2 John, Obadiah
    medium,     // Philippians, Ruth, James, Mark
    large;      // over ~20,000 words — Isaiah, Psalms, Genesis, Jeremiah

    /** Frame height of the handiwork on the room screen (build book §4.1). */
    val frameHeight: Double
        get() = when (this) {
            small -> 120.0
            medium -> 180.0
            large -> 240.0
        }

    companion object {
        operator fun invoke(wordCount: Int): FireScale {
            return if (wordCount < 750) {
                small
            } else if (wordCount <= 20_000) {
                medium
            } else {
                large
            }
        }
    }
}

/**
 * The section groupings used by the book chooser (S13). Editorial, not
 * theological — they exist so 66 rows read as a library, not a list.
 */
@Serializable
enum class BibleSection {
    @SerialName("The Law")
    law,

    @SerialName("History")
    history,

    @SerialName("Poetry & Wisdom")
    poetry,

    @SerialName("The Prophets")
    prophets,

    @SerialName("Gospels & Acts")
    gospels,

    @SerialName("Letters & Revelation")
    letters;

    /** The Swift raw value — what the section is called in the interface. */
    val raw: String
        get() = when (this) {
            law -> "The Law"
            history -> "History"
            poetry -> "Poetry & Wisdom"
            prophets -> "The Prophets"
            gospels -> "Gospels & Acts"
            letters -> "Letters & Revelation"
        }
}

/**
 * A book of the Bible. `id` is the standard USFM/paratext three-letter code,
 * which is also how notes and highlights address verses across translations.
 */
@Serializable
data class BibleBook(
    val id: String,
    val name: String,
    val section: BibleSection,
    val chapterCount: Int,
    /**
     * Word count of the World English Bible text, generated by
     * tools/usfx_to_json.py. Used only to derive the fire's scale —
     * never shown to a person (Law 2: no book-length numbers in the UI;
     * the drawn fire is the only length indicator).
     */
    val wordCount: Int
) {
    val scale: FireScale get() = FireScale(wordCount = wordCount)

    /**
     * The name a reference uses: the book is "Psalms," but a page heads a
     * single psalm "Psalm 23" and a citation reads "Psalm 23:1."
     */
    val referenceName: String
        get() = if (id == "PSA") "Psalm" else name

    /** "Mark 4" — or "Psalm 23," the way a printed page heads it. */
    fun chapterHeading(chapter: Int): String {
        return "$referenceName $chapter"
    }
}

object Bible {
    /** One section of the chooser and the books that sit under it. */
    data class SectionGroup(val section: BibleSection, val books: List<BibleBook>)

    /** All 66 books in canonical order. */
    val books: List<BibleBook> = generatedBooks

    /** Good places to start together (S13) — editorial, not algorithmic. */
    val goodPlacesToStart: List<String> = listOf("MRK", "RUT", "PHP", "JHN", "PSA")

    fun book(id: String): BibleBook? {
        return booksByID[id]
    }

    val sections: List<SectionGroup>
        get() = BibleSection.entries.mapNotNull { section ->
            val inSection = books.filter { it.section == section }
            if (inSection.isEmpty()) null else SectionGroup(section, inSection)
        }

    private val booksByID: Map<String, BibleBook> =
        books.associateBy { it.id }
}
