import Foundation

/// One handiwork per book, sized by the book (build book §2.9).
/// Size is set once from the book's word count when a reading opens, mapped
/// into three drawn sizes rather than a continuous scale — a continuous
/// scale invites comparison; three sizes read as a fact about the book.
/// Decision — the small/medium boundary. The build book's table says small
/// is "under ~5,000 words," but its own example columns contradict that:
/// Philippians (2,219 WEB words), Ruth (2,436) and James (2,249) are listed
/// as medium, while every listed small book is under 650. The examples
/// govern. The boundary sits at 750 — the natural gap in the real
/// distribution (Obadiah 619 → Titus 904) — so that exactly the named
/// books land small. The large boundary (~20,000) agrees with its examples
/// and stands.
public enum FireScale: String, Codable, Hashable, CaseIterable, Sendable {
    case small      // the single-sitting books — Philemon, Jude, 2 John, Obadiah
    case medium     // Philippians, Ruth, James, Mark
    case large      // over ~20,000 words — Isaiah, Psalms, Genesis, Jeremiah

    /// Frame height of the handiwork on the room screen (build book §4.1).
    public var frameHeight: Double {
        switch self {
        case .small: return 120
        case .medium: return 180
        case .large: return 240
        }
    }

    public init(wordCount: Int) {
        if wordCount < 750 {
            self = .small
        } else if wordCount <= 20_000 {
            self = .medium
        } else {
            self = .large
        }
    }
}

/// The section groupings used by the book chooser (S13). Editorial, not
/// theological — they exist so 66 rows read as a library, not a list.
public enum BibleSection: String, Codable, CaseIterable, Hashable, Sendable {
    case law = "The Law"
    case history = "History"
    case poetry = "Poetry & Wisdom"
    case prophets = "The Prophets"
    case gospels = "Gospels & Acts"
    case letters = "Letters & Revelation"
}

/// A book of the Bible. `id` is the standard USFM/paratext three-letter code,
/// which is also how notes and highlights address verses across translations.
public struct BibleBook: Codable, Hashable, Identifiable, Sendable {
    public let id: String
    public let name: String
    public let section: BibleSection
    public let chapterCount: Int
    /// Word count of the World English Bible text, generated by
    /// tools/usfx_to_json.py. Used only to derive the fire's scale —
    /// never shown to a person (Law 2: no book-length numbers in the UI;
    /// the drawn fire is the only length indicator).
    public let wordCount: Int

    public var scale: FireScale { FireScale(wordCount: wordCount) }
}

public enum Bible {
    /// All 66 books in canonical order.
    public static let books: [BibleBook] = generatedBooks

    /// Good places to start together (S13) — editorial, not algorithmic.
    public static let goodPlacesToStart: [String] = ["MRK", "RUT", "PHP", "JHN", "PSA"]

    public static func book(id: String) -> BibleBook? {
        booksByID[id]
    }

    public static var sections: [(section: BibleSection, books: [BibleBook])] {
        BibleSection.allCases.compactMap { section in
            let inSection = books.filter { $0.section == section }
            return inSection.isEmpty ? nil : (section, inSection)
        }
    }

    private static let booksByID: [String: BibleBook] =
        Dictionary(uniqueKeysWithValues: books.map { ($0.id, $0) })
}
